// SPDX-FileCopyrightText: 2022 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= qrtool(1)
// Specify in UTC.
:docdate: 2024-01-19
:doctype: manpage
ifdef::revnumber[:mansource: qrtool {revnumber}]
:manmanual: General Commands Manual
:includedir: ../include

== NAME

qrtool - an utility for encoding or decoding QR code

== SYNOPSIS

*{manname}* [_OPTION_]... _COMMAND_

== DESCRIPTION

*{manname}* is a command-line utility for encoding or decoding QR code.

== COMMANDS

*qrtool-encode*(1)::

  Encode input data in a QR code.

*qrtool-decode*(1)::

  Detect and decode a QR code.

*qrtool-help*(1)::

  Print the help for a command.

== OPTIONS

*-h*, *--help*::

  Print help message. The short flag (*-h*) will print a condensed help message
  while the long flag (*--help*) will print a detailed help message.

*-V*, *--version*::

  Print version number. The long flag (*--version*) will also print the
  copyright notice, the license notice and where to report bugs.

*--generate-completion* _SHELL_::

  Generate shell completion. The completion is output to stdout.

  The possible values are:{blank}:::

    *bash*::::

      Bash.

    *elvish*::::

      Elvish.

    *fish*::::

      fish.

    *nushell*::::

      Nushell.

    *powershell*::::

      PowerShell.

    *zsh*::::

      Zsh.

include::{includedir}/section-exit-status.adoc[]

== NOTES

Source repository:{blank}::

  https://github.com/sorairolake/qrtool

QR code.com:{blank}::

  https://www.qrcode.com/

include::{includedir}/section-reporting-bugs.adoc[]

include::{includedir}/section-copyright.adoc[]
