// SPDX-FileCopyrightText: 2022 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= qrtool(1)
// Specify in UTC.
:docdate: 2025-03-10
:revnumber: 0.11.8
:doctype: manpage
:mansource: qrtool {revnumber}
:manmanual: General Commands Manual
ifndef::site-gen-antora[:includedir: ./include]
:qrcode-url: https://www.qrcode.com/

== NAME

qrtool - an utility for encoding or decoding QR code

== SYNOPSIS

*{manname}* [_OPTION_]... _COMMAND_

== DESCRIPTION

*{manname}* is a command-line utility for encoding or decoding
{qrcode-url}[QR code].

== COMMANDS

*qrtool-encode*(1)::

  Encode input data in a QR code.

*qrtool-decode*(1)::

  Detect and decode a QR code.

*qrtool-completion*(1)::

  Generate shell completion.

*qrtool-help*(1)::

  Print the help for a command.

== OPTIONS

*-h*, *--help*::

  Print help message. The short flag (*-h*) will print a condensed help message
  while the long flag (*--help*) will print a detailed help message.

*-V*, *--version*::

  Print version number. The long flag (*--version*) will also print the
  copyright notice, the license notice and where to report bugs.

ifndef::site-gen-antora[include::{includedir}/section-exit-status.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-exit-status.adoc[]]

== NOTES

Source repository:{blank}::

  https://github.com/sorairolake/qrtool

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-copyright.adoc[]]
