// SPDX-FileCopyrightText: 2023 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= qrtool-help(1)
// Specify in UTC.
:docdate: 2024-07-30
:doctype: manpage
ifdef::revnumber[:mansource: qrtool {revnumber}]
ifndef::revnumber[:mansource: qrtool]
:manmanual: General Commands Manual
ifndef::site-gen-antora[:includedir: ./include]

== NAME

qrtool-help - print the help for a command

== SYNOPSIS

*qrtool help* [_COMMAND_]

== DESCRIPTION

This command prints the help for a command.

This command is identical to any of the following:{blank}::

  $ *qrtool* [_COMMAND_] *-h*|*--help*

== POSITIONAL ARGUMENTS

_COMMAND_::

  Subcommand to print the help.

ifndef::site-gen-antora[include::{includedir}/section-exit-status.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-exit-status.adoc[]]

== NOTES

Source repository:{blank}::

  https://github.com/sorairolake/qrtool

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-copyright.adoc[]]

== SEE ALSO

*qrtool*(1), *qrtool-decode*(1), *qrtool-encode*(1)
