//
// SPDX-License-Identifier: Apache-2.0 OR MIT
//
// Copyright (C) 2022-2023 Shun Sakai
//

= qrtool-decode(1)
// Specify in UTC.
:docdate: 2023-06-23
:doctype: manpage
ifdef::revnumber[:mansource: qrtool {revnumber}]
:manmanual: General Commands Manual
:includedir: ../include

== NAME

qrtool-decode - detect and decode a QR code

== SYNOPSIS

*qrtool decode* [_OPTION_]... [_IMAGE_]

== DESCRIPTION

This command detects and decodes a QR code.
By default, the result will be output to stdout.

== POSITIONAL ARGUMENTS

_IMAGE_::

  Input image file.
  If it is not specified, or if "-" is specified, the image will be read from
  stdin.
  Supported raster image formats are based on the formats supported by the
  image crate.
  The format guess based on the extension, and the raster format use the
  content in addition to it.
  If the format cannot be guessed, use *--type*.
  Note that the SVG image is rasterized before scanning.

== OPTIONS

*-t*, *--type* _FORMAT_::

  The format of the input.
  If it is not specified, the format will be guessed based on the extension,
  and the raster format will use the content in addition to it.

  The possible values are:{blank}:::

    *bmp*::::

      Windows Bitmap.

    *dds*::::

      DirectDraw Surface.

    *farbfeld*::::

      Farbfeld.

    *gif*::::

      Graphics Interchange Format.

    *hdr*::::

      Radiance RGBE.

    *ico*::::

      ICO file format.
      This also includes the CUR file format.

    *jpeg*::::

      JPEG.

    *openexr*::::

      OpenEXR.

    *png*::::

      Portable Network Graphics.

    *pnm*::::

      Portable Anymap Format (PBM, PGM and PPM).

    *qoi*::::

      Quite OK Image Format.

ifdef::decode-from-svg[]
    *svg*::::

      Scalable Vector Graphics.
      This also includes gzipped it.
endif::[]

    *tga*::::

      Truevision TGA.

    *tiff*::::

      Tag Image File Format.

    *webp*::::

      WebP.

*--verbose*::

  Also print the metadata.
  It is output to stderr.
  This conflicts with *--metadata*.

*--metadata*::

  Print only the metadata.
  It is output to stderr.
  This conflicts with *--verbose*.

*-h*, *--help*::

  Print help information.

*-V*, *--version*::

  Print version information.

include::{includedir}/section-exit-status.adoc[]

== EXAMPLES

Detect and decode a QR code from the given image:{blank}::

  $ *qrtool decode input.png*

include::{includedir}/section-reporting-bugs.adoc[]

include::{includedir}/section-copyright.adoc[]

== SEE ALSO

*qrtool*(1), *qrtool-encode*(1)
