// SPDX-FileCopyrightText: 2022 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= qrtool-decode(1)
// Specify in UTC.
:docdate: 2023-07-17
:doctype: manpage
ifdef::revnumber[:mansource: qrtool {revnumber}]
:manmanual: General Commands Manual
:includedir: ../include

== NAME

qrtool-decode - detect and decode a QR code

== SYNOPSIS

*qrtool decode* [_OPTION_]... [_IMAGE_]

== DESCRIPTION

This command detects and decodes a QR code. By default, the result will be
output to stdout.

== POSITIONAL ARGUMENTS

_IMAGE_::

  Input image file. If _IMAGE_ is not specified, or if "-" is specified, the
  image will be read from stdin. Supported raster image formats are based on
  the formats supported by the image crate. The format of _IMAGE_ is determined
  based on the extension or the magic number if possible. If the format cannot
  be determined, use *--type*. Note that the SVG image is rasterized before
  scanning.

== OPTIONS

*-t*, *--type* _FORMAT_::

  The format of the input. If _FORMAT_ is not specified, the format is
  determined based on the extension or the magic number.

  The possible values are:{blank}:::

    *bmp*::::

      Windows Bitmap.

    *dds*::::

      DirectDraw Surface.

    *farbfeld*::::

      Farbfeld.

    *gif*::::

      Graphics Interchange Format.

    *hdr*::::

      Radiance RGBE.

    *ico*::::

      ICO file format. This value also includes the CUR file format.

    *jpeg*::::

      JPEG.

    *openexr*::::

      OpenEXR.

    *png*::::

      Portable Network Graphics.

    *pnm*::::

      Portable Anymap Format.

    *qoi*::::

      Quite OK Image Format.

ifdef::decode-from-svg,env-github[]
    *svg*::::

      Scalable Vector Graphics. This value also includes the gzip-compressed
      SVG image.
endif::[]

    *tga*::::

      Truevision TGA.

    *tiff*::::

      Tag Image File Format.

    *webp*::::

      WebP.

*--verbose*::

  Also print the metadata. It is output to stderr. This option conflicts with
  *--metadata*.

*--metadata*::

  Print only the metadata. It is output to stderr. This option conflicts with
  *--verbose*.

*-h*, *--help*::

  Print help information.

*-V*, *--version*::

  Print version information.

include::{includedir}/section-exit-status.adoc[]

== NOTES

Source repository:{blank}::

  https://github.com/sorairolake/qrtool

QR code.com:{blank}::

  https://www.qrcode.com/

image crate:{blank}::

  https://crates.io/crates/image

== EXAMPLES

Detect and decode a QR code from the given image:{blank}::

  $ *qrtool decode input.png*

include::{includedir}/section-reporting-bugs.adoc[]

include::{includedir}/section-copyright.adoc[]

== SEE ALSO

*qrtool*(1), *qrtool-encode*(1), *qrtool-help*(1), *zbarimg*(1)
