//
// SPDX-License-Identifier: Apache-2.0 OR MIT
//
// Copyright (C) 2022-2023 Shun Sakai
//

= qrtool-encode(1)
// Specify in UTC.
:docdate: 2023-07-08
:doctype: manpage
ifdef::revnumber[:mansource: qrtool {revnumber}]
:manmanual: General Commands Manual
:includedir: ../include

== NAME

qrtool-encode - encode input data in a QR code

== SYNOPSIS

*qrtool encode* [_OPTION_]... [_STRING_]

== DESCRIPTION

This command encodes input data in a QR code.
By default, the result will be output to stdout.

== POSITIONAL ARGUMENTS

_STRING_::

  Input data.
  If _STRING_ is not specified, data will be read from stdin.
  _STRING_ must be a valid UTF-8 string.
  Use *--read-from* or read from stdin if taking other than a valid UTF-8
  string.
  This positional argument conflicts with *--read-from*.

== OPTIONS

*-o*, *--output* _FILE_::

  Output the result to a file.

*-r*, *--read-from* _FILE_::

  Read input data from a file.
  This option conflicts with _STRING_.

*-l*, *--error-correction-level* _LEVEL_::

  Error correction level.

  The possible values are:{blank}:::

    *l*::::

      Level L.
      7% of codewords can be restored.

    *m*::::

      Level M.
      15% of codewords can be restored.
      This is the default value.

    *q*::::

      Level Q.
      25% of codewords can be restored.

    *h*::::

      Level H.
      30% of codewords can be restored.

*--level* _LEVEL_::

  Alias for *-l*, *--error-correction-level*.

*-v*, *--symbol-version* _NUMBER_::

  The version of the symbol.
  For normal QR code, _NUMBER_ should be between *1* and *40*.
  For Micro QR code, _NUMBER_ should be between *1* and *4*.

*--symversion* _NUMBER_::

  Alias for *-v*, *--symbol-version*.

*-m*, *--margin* _NUMBER_::

  The width of margin.
  Default is 4.

*-t*, *--type* _FORMAT_::

  The format of the output.

  The possible values are:{blank}:::

    *png*::::

      Portable Network Graphics.
      This outputs 32-bit RGBA PNG image.
      This is the default value.

    *svg*::::

      Scalable Vector Graphics.

    *terminal*::::

      To the terminal as UTF-8 string.

*--mode* _MODE_::

  The mode of the output.

  The possible values are:{blank}:::

    *numeric*::::

      All digits.

    *alphanumeric*::::

      Alphanumerics and few symbols.

    *byte*::::

      Arbitrary binary data.
      This is the default value.

    *kanji*::::

      Shift JIS text.

*--variant* _TYPE_::

  The type of QR code.
  This option requires *--symbol-version*.

  The possible values are:{blank}:::

    *normal*::::

      Normal QR code.
      This is the default value.

    *micro*::::

      Micro QR code.

*--foreground* _COLOR_::

  Foreground color.
  _COLOR_ takes a CSS color string.
  Default is black.

*--background* _COLOR_::

  Background color.
  _COLOR_ takes a CSS color string.
  Default is white.

*--verbose*::

  Also print the metadata.
  It is output to stderr.

*-h*, *--help*::

  Print help information.

*-V*, *--version*::

  Print version information.

include::{includedir}/section-exit-status.adoc[]

== NOTES

Source repository:{blank}::

  https://github.com/sorairolake/qrtool

QR code.com:{blank}::

  https://www.qrcode.com/

CSS Color Module Level 4:{blank}::

  https://www.w3.org/TR/css-color-4/

== EXAMPLES

Encode the given string in a QR code:{blank}::

  $ *qrtool encode "QR code"*

include::{includedir}/section-reporting-bugs.adoc[]

include::{includedir}/section-copyright.adoc[]

== SEE ALSO

*qrencode*(1), *qrtool*(1), *qrtool-decode*(1)
